### ISSUE TITLE
Incompatible with foreigner

### ISSUE THREAD

**Issue by c1n1c** [pinnymz/migration_comments#20]
It looks like migration_comments break foreigner AR::ConnectionAdapters extensions. Both gems extending create_table method for migrations. And if I add migration_comments gem to my Rails 4.1 project with installed foreigner, in migrations like this

```
create_table :profiles do |t|
  ...
  t.references :user
  t.foreign_key :users
  ...
end
```

foreign_key stops working without any error messages. Debugging shows that overridden in foreigner create_table method is not called.

I think the problem is in how migration_comments gem initialized. I tried to add railtie

lib/migration_comments/railtie.rb:
```
module MigrationComments
  class Railtie < Rails::Railtie
    initializer 'migration_comments.load_adapter' do
      ActiveSupport.on_load :active_record do
        MigrationComments.setup
      end
    end
  end
end
```

and move gem setup to it

lib/migration_comments.rb:
```
...
# MigrationComments.setup
require 'migration_comments/railtie' if defined?(Rails)
```

and it solved the problem. Both gems work fine.

**Comment by pinnymz** [comment]
@c1n1c can you try this using #30 branch and see if the problem persists?

**Comment by c1n1c** [comment]
actually we already using this version (5e909afc) since 13 May 2015) it works fine with Rails 4.2, but I can't check that it's compatible with Foreigner, because we have stoped using Foreigner after moving to Rails 4.2 with it's own foreign keys helpers.

**Comment by pinnymz** [comment]
Very well then, I'll mark this as closed.
