### ISSUE TITLE
Varchar primary key fields with name other than id changed to int(11) ai

### ISSUE THREAD

**Issue by arcasys** [pinnymz/migration_comments#25]
Varchar primary key fields with name other than id get redefined in a wrong way when migration_comments is run: Such PK fields arre converted to type integer(11) with auto increment and their content is recreated accordingly as sequential numbers.
The original content is lost which makes the otherwise perfect gem unusable for legacy databases containing primary keys with names other than 'id'.

Example: 

    Columns:
    property_key	varchar(255) PK 
    value	varchar(255) 

comes out as 

    Columns:
    property_key	int(11) PK AI
    value	varchar(255) 

Tested with rails 2.3.18, migration_comments 0.3.2. This is even when id fields are not included

**Comment by pinnymz** [comment]
Hi @arcasys thanks for the report.  What DB are you using?

**Comment by arcasys** [comment]
Am 13.11.2015 13:55, schrieb pinnymz:
>
> Hi @arcasys <https://github.com/arcasys> thanks for the report. What 
> DB are you using?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pinnymz/migration_comments/issues/25#issuecomment-156425450>.
>
MySQL
The connector is mysql2 (0.3.16)

-- 
arcasys
Kassensysteme
Warenwirtschaft
Vernetzung
__________________________
*Hans Artmann*
Wotanstr. 82
80639 München
Tel +49 89 17095721
Fax +49 89 17095722
Mob +49 151 27007919
www.arcasys.de <http://www.arcasys.de>

Ust-Id: DE261339573

**Comment by pinnymz** [comment]
There is an outstanding PR that fixes a similar problem - can you try using the `fix_for_postgres_uuid` branch and see if that works for you?  Also, please note that Rails 2 support has been deprecated and should not be expected to work for future releases.

**Comment by pinnymz** [comment]
This is now addressed in #30
