### ISSUE TITLE
Changing column comment crashes with Postgresql

### ISSUE THREAD

**Issue by urmorae** [pinnymz/migration_comments#26]
change_table :table1 do |t|
  t.change_comment :column1, 'comment text'
end

crashes as table name is correcty fetched in
lib/migration_comments/active_record/connection_adapters/table.rb

def change_comment(column_name, comment_text)
  @base.set_column_comment(@table_name, column_name, comment_text)
end

@table_name seems to be not initialized. What is, is @table.

I'm using PostgreSQL adapter, AR 4.2.4, 0.3.2 migration_comments

**Comment by pinnymz** [comment]
@urmorae this should be fixed in latest master, please confirm if that works

**Comment by urmorae** [comment]
@pinnymz yes, master works perfectly
