### ISSUE TITLE
set_column_comment to MySQL bigint(20) primary_key revert to int(11)

### ISSUE THREAD

**Issue by showwin** [pinnymz/migration_comments#37]
Hi 😀 

I use v0.3.2 with ActiveRecord v4.2.6.
I have tried to create table with a bigint(20) as primary_key with comment for MySQL, though If I use `set_column_comment` to the primary_key, its type become int(11).

In concrete, migration file is

```
class CreateTests < ActiveRecord::Migration
  def change
    create_table :tests, id: false do |t|
      t.column  :id, 'BIGINT PRIMARY KEY AUTO_INCREMENT'
      t.string :name
    end
    set_column_comment :tests, :id, "TestID"
  end
end
```

and result(`structure.sql`) is `int(11)`, not `bigint(20)`.

```
CREATE TABLE `tests` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'TestID',
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

When I remove `set_column_comment`,

```
class CreateTests < ActiveRecord::Migration
  def change
    create_table :tests, id: false do |t|
      t.column  :id, 'BIGINT PRIMARY KEY AUTO_INCREMENT'
      t.string :name
    end
  end
end
```

`structure.sql` is what I expected. (but I need `COMMENT 'TestID'`)

```
CREATE TABLE `tests` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Fortunately, I've already found the solution. At `set_column_comment` method of [v0.3.2](https://github.com/pinnymz/migration_comments/blob/v0.3.2/lib/migration_comments/active_record/connection_adapters/mysql_adapter.rb#L18), doing the same way of [master](https://github.com/pinnymz/migration_comments/blob/ce5f996dfd3ea03463f7d5cd40854aa10b6ea973/lib/migration_comments/active_record/connection_adapters/mysql2_adapter.rb#L12) goes well.
Therefore I want to make a Pull Request to fix this problem. Though, this repository has only `master` branch, no branch for v0.3.x. What should I do to fix this bug and release v0.3.3 for ActiveRecord prior to v4.2.

**Comment by pinnymz** [comment]
I'm sorry, but we're not going to be maintaining previous versions.  I think you have 3 options:
- Update to latest gem version (0.4.1 at this time)
- Lock your Gemfile to this commit (https://github.com/pinnymz/migration_comments/pull/15/commits/c47d86df8d6d95bae9105ec9e9bdff61a1d1e0f7) that addresses your problem (also see #15): 
- Fork and fix it however you like

**Comment by showwin** [comment]
Thank you for quick response !

> Update to latest gem version (0.4.1 at this time)

This works fine with ActiveRecord v4.2.6 👍 

I'm sorry, I misunderstood the meaning of

> ActiveRecord prior to 4.2, please use the v0.3.2
